/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.Gestion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import validaciones.Validar;

/**
 *
 * @author vina
 */
public class Vista_principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista_principal
     */
    public Vista_principal() {
        initComponents();
    }
    
    public void limpiarCampos (){
        this.jTextField_RUT.setText("");
        this.jTextField_NOMBRE_COMPLETO.setText("");
        this.jTextField_CORREO.setText("");
        this.jTextField_TELEFONO.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_LISTAR = new javax.swing.JButton();
        jButton_AGREGAR = new javax.swing.JButton();
        jButton_LIMPIAR = new javax.swing.JButton();
        jTextField_RUT = new javax.swing.JTextField();
        jTextField_NOMBRE_COMPLETO = new javax.swing.JTextField();
        jTextField_TELEFONO = new javax.swing.JTextField();
        jTextField_CORREO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "NOMBRE", "TELEFONO", "CORREO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("RUT");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setText("REGISTRO CLIENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("NOMBRE COMPLETO");

        jLabel3.setText("TELEFONO");

        jLabel4.setText("CORREO");

        jButton_LISTAR.setText("LISTAR");
        jButton_LISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LISTARActionPerformed(evt);
            }
        });

        jButton_AGREGAR.setText("AGREGAR");
        jButton_AGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AGREGARActionPerformed(evt);
            }
        });

        jButton_LIMPIAR.setText("LIMPIAR");
        jButton_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LIMPIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_LIMPIAR)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_AGREGAR)
                        .addGap(29, 29, 29)
                        .addComponent(jButton_LISTAR))
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_CORREO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(jTextField_TELEFONO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_NOMBRE_COMPLETO, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_NOMBRE_COMPLETO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_CORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_LIMPIAR)
                            .addComponent(jButton_AGREGAR)
                            .addComponent(jButton_LISTAR)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AGREGARActionPerformed
        String rut,nombre,correo;
        int telefono;
        Gestion  gest = new Gestion();
        
        if(Validar.camposVacios(this.jTextField_RUT.getText()) ||
           Validar.camposVacios(this.jTextField_NOMBRE_COMPLETO.getText()) ||
           Validar.camposVacios(this.jTextField_CORREO.getText()) ||
           Validar.camposVacios(this.jTextField_TELEFONO.getText()))
        {
            JOptionPane.showMessageDialog(this, "complete los campos");
        } else {
            try {
                rut=this.jTextField_RUT.getText();
                nombre=this.jTextField_NOMBRE_COMPLETO.getText();
                correo=this.jTextField_CORREO.getText();
                telefono=Integer.parseInt(this.jTextField_TELEFONO.getText());
                Cliente cli = new Cliente(rut, nombre, correo, telefono);
                gest.agregarCliente(cli);
                JOptionPane.showMessageDialog(this, "cliente agregado","AGREGAR CLIENTE",1);
                limpiarCampos();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this , " el telefono debe ser ingresado con numeros ");
            }
            
        
        }
        
        
        
    }//GEN-LAST:event_jButton_AGREGARActionPerformed

    private void jButton_LISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LISTARActionPerformed
        String rut,nombre,correo;
        int telefono;
        Gestion gest = new Gestion();
        DefaultTableModel modelo = (DefaultTableModel)this.jTable1.getModel();
        modelo.setRowCount(0);
        
        ArrayList<Cliente> lista = gest.listarclientestabla();
        for (Cliente cli : lista) {
            rut=cli.getRut();
            nombre=cli.getNombre_completo();
            correo=cli.getCorreo();
            telefono=cli.getTelefono();
            
            modelo.addRow(new Object[] {rut,nombre,correo,telefono});
        }
    }//GEN-LAST:event_jButton_LISTARActionPerformed

    private void jButton_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LIMPIARActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_jButton_LIMPIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AGREGAR;
    private javax.swing.JButton jButton_LIMPIAR;
    private javax.swing.JButton jButton_LISTAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_CORREO;
    private javax.swing.JTextField jTextField_NOMBRE_COMPLETO;
    private javax.swing.JTextField jTextField_RUT;
    private javax.swing.JTextField jTextField_TELEFONO;
    // End of variables declaration//GEN-END:variables
}

